//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 02:58:18 PM PDT 
//


package newance.psmconverter.pepxml_v120;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for massType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="massType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="monoisotopic"/>
 *     &lt;enumeration value="average"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "massType")
@XmlEnum
public enum MassType {

    @XmlEnumValue("monoisotopic")
    MONOISOTOPIC("monoisotopic"),
    @XmlEnumValue("average")
    AVERAGE("average");
    private final String value;

    MassType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MassType fromValue(String v) {
        for (MassType c: MassType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
