//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 02:58:18 PM PDT 
//


package newance.psmconverter.pepxml_v120;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Positions and masses of modifications
 * 
 * <p>Java class for modInfoDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modInfoDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mod_aminoacid_mass" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="position" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="mass" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="static" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="variable" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="aminoacid_substitution" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="orig_aa" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="num_tol_term" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *                 &lt;attribute name="peptide_prev_aa" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="peptide_next_aa" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="mod_nterm_mass" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="mod_cterm_mass" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="modified_peptide" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modInfoDataType", propOrder = {
    "modAminoacidMass",
    "aminoacidSubstitution"
})
public class ModInfoDataType {

    @XmlElement(name = "mod_aminoacid_mass")
    protected List<ModInfoDataType.ModAminoacidMass> modAminoacidMass;
    @XmlElement(name = "aminoacid_substitution")
    protected List<ModInfoDataType.AminoacidSubstitution> aminoacidSubstitution;
    @XmlAttribute(name = "mod_nterm_mass")
    protected Double modNtermMass;
    @XmlAttribute(name = "mod_cterm_mass")
    protected Double modCtermMass;
    @XmlAttribute(name = "modified_peptide")
    protected String modifiedPeptide;

    /**
     * Gets the value of the modAminoacidMass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modAminoacidMass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModAminoacidMass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModInfoDataType.ModAminoacidMass }
     * 
     * 
     */
    public List<ModInfoDataType.ModAminoacidMass> getModAminoacidMass() {
        if (modAminoacidMass == null) {
            modAminoacidMass = new ArrayList<ModInfoDataType.ModAminoacidMass>();
        }
        return this.modAminoacidMass;
    }

    /**
     * Gets the value of the aminoacidSubstitution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aminoacidSubstitution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAminoacidSubstitution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModInfoDataType.AminoacidSubstitution }
     * 
     * 
     */
    public List<ModInfoDataType.AminoacidSubstitution> getAminoacidSubstitution() {
        if (aminoacidSubstitution == null) {
            aminoacidSubstitution = new ArrayList<ModInfoDataType.AminoacidSubstitution>();
        }
        return this.aminoacidSubstitution;
    }

    /**
     * Gets the value of the modNtermMass property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getModNtermMass() {
        return modNtermMass;
    }

    /**
     * Sets the value of the modNtermMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setModNtermMass(Double value) {
        this.modNtermMass = value;
    }

    /**
     * Gets the value of the modCtermMass property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getModCtermMass() {
        return modCtermMass;
    }

    /**
     * Sets the value of the modCtermMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setModCtermMass(Double value) {
        this.modCtermMass = value;
    }

    /**
     * Gets the value of the modifiedPeptide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedPeptide() {
        return modifiedPeptide;
    }

    /**
     * Sets the value of the modifiedPeptide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedPeptide(String value) {
        this.modifiedPeptide = value;
    }


    /**
     * Peptide found via aminoacid substitution. Can apply to represent a substitution within peptide sequence, and/or on flanking residues
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="orig_aa" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="num_tol_term" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="peptide_prev_aa" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="peptide_next_aa" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AminoacidSubstitution {

        @XmlAttribute(name = "position")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger position;
        @XmlAttribute(name = "orig_aa")
        protected String origAa;
        @XmlAttribute(name = "num_tol_term")
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger numTolTerm;
        @XmlAttribute(name = "peptide_prev_aa")
        protected String peptidePrevAa;
        @XmlAttribute(name = "peptide_next_aa")
        protected String peptideNextAa;

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPosition(BigInteger value) {
            this.position = value;
        }

        /**
         * Gets the value of the origAa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigAa() {
            return origAa;
        }

        /**
         * Sets the value of the origAa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigAa(String value) {
            this.origAa = value;
        }

        /**
         * Gets the value of the numTolTerm property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumTolTerm() {
            return numTolTerm;
        }

        /**
         * Sets the value of the numTolTerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumTolTerm(BigInteger value) {
            this.numTolTerm = value;
        }

        /**
         * Gets the value of the peptidePrevAa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeptidePrevAa() {
            return peptidePrevAa;
        }

        /**
         * Sets the value of the peptidePrevAa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeptidePrevAa(String value) {
            this.peptidePrevAa = value;
        }

        /**
         * Gets the value of the peptideNextAa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPeptideNextAa() {
            return peptideNextAa;
        }

        /**
         * Sets the value of the peptideNextAa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPeptideNextAa(String value) {
            this.peptideNextAa = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="position" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
     *       &lt;attribute name="mass" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="static" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="variable" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="source" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ModAminoacidMass {

        @XmlAttribute(name = "position", required = true)
        @XmlSchemaType(name = "nonNegativeInteger")
        protected BigInteger position;
        @XmlAttribute(name = "mass", required = true)
        protected double mass;
        @XmlAttribute(name = "static")
        protected Double _static;
        @XmlAttribute(name = "variable")
        protected Double variable;
        @XmlAttribute(name = "source")
        protected String source;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPosition(BigInteger value) {
            this.position = value;
        }

        /**
         * Gets the value of the mass property.
         * 
         */
        public double getMass() {
            return mass;
        }

        /**
         * Sets the value of the mass property.
         * 
         */
        public void setMass(double value) {
            this.mass = value;
        }

        /**
         * Gets the value of the static property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getStatic() {
            return _static;
        }

        /**
         * Sets the value of the static property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setStatic(Double value) {
            this._static = value;
        }

        /**
         * Gets the value of the variable property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getVariable() {
            return variable;
        }

        /**
         * Sets the value of the variable property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setVariable(Double value) {
            this.variable = value;
        }

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSource(String value) {
            this.source = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
