//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.28 at 02:58:18 PM PDT 
//


package newance.psmconverter.pepxml_v120;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.systemsbiology.regis_web.pepxml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.systemsbiology.regis_web.pepxml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis }
     * 
     */
    public MsmsPipelineAnalysis createMsmsPipelineAnalysis() {
        return new MsmsPipelineAnalysis();
    }

    /**
     * Create an instance of {@link ModInfoDataType }
     * 
     */
    public ModInfoDataType createModInfoDataType() {
        return new ModInfoDataType();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary createMsmsPipelineAnalysisMsmsRunSummary() {
        return new MsmsPipelineAnalysis.MsmsRunSummary();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery createMsmsPipelineAnalysisMsmsRunSummarySpectrumQuery() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult createMsmsPipelineAnalysisMsmsRunSummarySpectrumQuerySearchResult() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit createMsmsPipelineAnalysisMsmsRunSummarySpectrumQuerySearchResultSearchHit() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.Xlink }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.Xlink createMsmsPipelineAnalysisMsmsRunSummarySpectrumQuerySearchResultSearchHitXlink() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.Xlink();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary createMsmsPipelineAnalysisMsmsRunSummarySearchSummary() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SampleEnzyme }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SampleEnzyme createMsmsPipelineAnalysisMsmsRunSummarySampleEnzyme() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SampleEnzyme();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.DatasetDerivation }
     * 
     */
    public MsmsPipelineAnalysis.DatasetDerivation createMsmsPipelineAnalysisDatasetDerivation() {
        return new MsmsPipelineAnalysis.DatasetDerivation();
    }

    /**
     * Create an instance of {@link InputFileType }
     * 
     */
    public InputFileType createInputFileType() {
        return new InputFileType();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.AnalysisSummary }
     * 
     */
    public MsmsPipelineAnalysis.AnalysisSummary createMsmsPipelineAnalysisAnalysisSummary() {
        return new MsmsPipelineAnalysis.AnalysisSummary();
    }

    /**
     * Create an instance of {@link NameValueType }
     * 
     */
    public NameValueType createNameValueType() {
        return new NameValueType();
    }

    /**
     * Create an instance of {@link AltProteinDataType }
     * 
     */
    public AltProteinDataType createAltProteinDataType() {
        return new AltProteinDataType();
    }

    /**
     * Create an instance of {@link ModInfoDataType.ModAminoacidMass }
     * 
     */
    public ModInfoDataType.ModAminoacidMass createModInfoDataTypeModAminoacidMass() {
        return new ModInfoDataType.ModAminoacidMass();
    }

    /**
     * Create an instance of {@link ModInfoDataType.AminoacidSubstitution }
     * 
     */
    public ModInfoDataType.AminoacidSubstitution createModInfoDataTypeAminoacidSubstitution() {
        return new ModInfoDataType.AminoacidSubstitution();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.CrossLinker }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.CrossLinker createMsmsPipelineAnalysisMsmsRunSummaryCrossLinker() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.CrossLinker();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.AnalysisTimestamp }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.AnalysisTimestamp createMsmsPipelineAnalysisMsmsRunSummaryAnalysisTimestamp() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.AnalysisTimestamp();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.AnalysisResult }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.AnalysisResult createMsmsPipelineAnalysisMsmsRunSummarySpectrumQuerySearchResultSearchHitAnalysisResult() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.AnalysisResult();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.Xlink.LinkedPeptide }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.Xlink.LinkedPeptide createMsmsPipelineAnalysisMsmsRunSummarySpectrumQuerySearchResultSearchHitXlinkLinkedPeptide() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SpectrumQuery.SearchResult.SearchHit.Xlink.LinkedPeptide();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.SearchDatabase }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.SearchDatabase createMsmsPipelineAnalysisMsmsRunSummarySearchSummarySearchDatabase() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.SearchDatabase();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.EnzymaticSearchConstraint }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.EnzymaticSearchConstraint createMsmsPipelineAnalysisMsmsRunSummarySearchSummaryEnzymaticSearchConstraint() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.EnzymaticSearchConstraint();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.SequenceSearchConstraint }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.SequenceSearchConstraint createMsmsPipelineAnalysisMsmsRunSummarySearchSummarySequenceSearchConstraint() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.SequenceSearchConstraint();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.AminoacidModification }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.AminoacidModification createMsmsPipelineAnalysisMsmsRunSummarySearchSummaryAminoacidModification() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.AminoacidModification();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.TerminalModification }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.TerminalModification createMsmsPipelineAnalysisMsmsRunSummarySearchSummaryTerminalModification() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SearchSummary.TerminalModification();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.MsmsRunSummary.SampleEnzyme.Specificity }
     * 
     */
    public MsmsPipelineAnalysis.MsmsRunSummary.SampleEnzyme.Specificity createMsmsPipelineAnalysisMsmsRunSummarySampleEnzymeSpecificity() {
        return new MsmsPipelineAnalysis.MsmsRunSummary.SampleEnzyme.Specificity();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis.DatasetDerivation.DataFilter }
     * 
     */
    public MsmsPipelineAnalysis.DatasetDerivation.DataFilter createMsmsPipelineAnalysisDatasetDerivationDataFilter() {
        return new MsmsPipelineAnalysis.DatasetDerivation.DataFilter();
    }

}
