//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.04 at 12:29:48 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://regis-web.systemsbiology.net/pepXML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package newance.psmconverter.pepxml_v120;
